/**
 * POST /api/invitations  — send an invitation
 * GET  /api/invitations  — list pending invitations in active org
 *
 * Architecture decision — token-based invitations:
 *   The invitation row carries a cryptographically random token
 *   generated by PostgreSQL (encode(gen_random_bytes(32), 'hex')).
 *   The email contains a link to /invite/[token].
 *   Accepting the invite creates the membership and marks the invite
 *   as accepted. Expired or accepted tokens are rejected.
 *
 * No email service is wired yet (Fas 4). The token is returned in the
 * response so it can be shared manually during development.
 */

import { prisma } from "@/lib/prisma"
import { requireAuth } from "@/lib/rbac/guards"
import { canOrThrow } from "@/lib/rbac/policy"
import { writeAuditLog } from "@/lib/tenant-db"
import { z } from "zod"

const InviteSchema = z.object({
  email: z.string().email(),
  role:  z.enum(["owner", "admin", "member", "viewer"]).default("member"),
})

// ─── POST /api/invitations ───────────────────────────────────────────

export async function POST(req: Request) {
  try {
    const ctx = await requireAuth()
    canOrThrow(ctx, "users:invite")

    const body = await req.json()
    const parsed = InviteSchema.safeParse(body)
    if (!parsed.success) {
      return Response.json({ error: "Ogiltiga uppgifter" }, { status: 400 })
    }

    const { email, role } = parsed.data
    const normalizedEmail = email.toLowerCase()

    // Owners can't be invited — they're created at registration
    if (role === "owner") {
      return Response.json({ error: "Ägarrollen kan inte bjudas in" }, { status: 400 })
    }

    // Check: is the user already a member?
    const existingUser = await prisma.user.findUnique({
      where: { email: normalizedEmail },
      select: { id: true },
    })

    if (existingUser) {
      const existingMembership = await prisma.organizationMember.findUnique({
        where: {
          organizationId_userId: {
            organizationId: ctx.organizationId,
            userId: existingUser.id,
          },
        },
      })
      if (existingMembership && !existingMembership.deletedAt) {
        return Response.json({ error: "Användaren är redan medlem" }, { status: 409 })
      }
    }

    // Upsert invitation (reset token + expiry if re-inviting)
    const invitation = await prisma.invitation.upsert({
      where: {
        organizationId_email: {
          organizationId: ctx.organizationId,
          email: normalizedEmail,
        },
      },
      create: {
        organizationId: ctx.organizationId,
        email: normalizedEmail,
        role,
        invitedBy: ctx.userId,
      },
      update: {
        role,
        invitedBy: ctx.userId,
        acceptedAt: null,
        // Reset token and expiry by nullifying then re-defaulting
        // (Prisma doesn't support calling DB functions in update,
        //  so we manually set a new token here)
        token: generateToken(),
        expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
      },
    })

    await writeAuditLog({
      ctx,
      action: "invite_send",
      entityType: "invitation",
      entityId: invitation.id,
      meta: { email: normalizedEmail, role },
      ipAddress: req.headers.get("x-forwarded-for") ?? undefined,
    })

    // TODO (Fas 4): send email via Resend
    // await sendInvitationEmail({ to: normalizedEmail, token: invitation.token, orgName })

    return Response.json({
      id:        invitation.id,
      email:     invitation.email,
      role:      invitation.role,
      expiresAt: invitation.expiresAt,
      // Included for development — remove before production
      inviteUrl: `${process.env.NEXTAUTH_URL}/invite/${invitation.token}`,
    }, { status: 201 })

  } catch (err: unknown) {
    if ((err as { name?: string }).name === "UnauthorizedError") {
      return Response.json({ error: "Otillräckliga rättigheter" }, { status: 403 })
    }
    if ((err as { name?: string }).name === "UnauthenticatedError") {
      return Response.json({ error: "Ej inloggad" }, { status: 401 })
    }
    console.error("[invitations POST]", err)
    return Response.json({ error: "Internt fel" }, { status: 500 })
  }
}

// ─── GET /api/invitations ────────────────────────────────────────────

export async function GET() {
  try {
    const ctx = await requireAuth()
    canOrThrow(ctx, "users:read")

    const invitations = await prisma.invitation.findMany({
      where: {
        organizationId: ctx.organizationId,
        acceptedAt: null,
        expiresAt: { gt: new Date() },
      },
      select: {
        id:        true,
        email:     true,
        role:      true,
        expiresAt: true,
        createdAt: true,
        invitedByUser: { select: { fullName: true, email: true } },
      },
      orderBy: { createdAt: "desc" },
    })

    return Response.json({ invitations })

  } catch {
    return Response.json({ error: "Ej inloggad" }, { status: 401 })
  }
}

// ─────────────────────────────────────────────
// Helper
// ─────────────────────────────────────────────

function generateToken(): string {
  const bytes = new Uint8Array(32)
  crypto.getRandomValues(bytes)
  return Array.from(bytes).map((b) => b.toString(16).padStart(2, "0")).join("")
}
