/**
 * Endoo RBAC — Role definitions
 *
 * System roles are DERIVED at runtime — they are NOT stored directly in the DB.
 * The source of truth is:
 *   User.isPlatformAdmin           → "super_admin"
 *   Organization.type + OrganizationMember.role → one of the org roles below
 *
 * Derivation map:
 *   isPlatformAdmin = true                                → super_admin
 *   org.type = 'agency'  + member.role = 'owner'         → agency_owner
 *   org.type = 'agency'  + member.role = 'admin'         → agency_admin
 *   org.type = 'agency'  + member.role = 'member'        → agency_staff
 *   org.type = 'agency'  + member.role = 'viewer'        → agency_viewer
 *   org.type = 'customer'+ member.role = 'owner'         → customer_owner
 *   org.type = 'customer'+ member.role = 'admin'         → customer_admin
 *   org.type = 'customer'+ member.role = 'member'        → customer_user
 *   org.type = 'customer'+ member.role = 'viewer'        → customer_viewer
 *
 * When an agency impersonates a client the effective role is resolved
 * against the client org — see context.ts for that logic.
 */

import {
  PLATFORM_PERMISSIONS,
  INVOICE_PERMISSIONS,
  CONTACT_PERMISSIONS,
  PRODUCT_PERMISSIONS,
  PAYMENT_PERMISSIONS,
  CONTRACT_PERMISSIONS,
  USER_PERMISSIONS,
  SETTINGS_PERMISSIONS,
  REPORT_PERMISSIONS,
  ACCOUNTING_PERMISSIONS,
  SUPPLIER_INVOICE_PERMISSIONS,
  INVENTORY_PERMISSIONS,
  AGENCY_PERMISSIONS,
  TASK_PERMISSIONS,
  SIGNATURE_PERMISSIONS,
  QUOTE_PERMISSIONS,
  BRANDING_PERMISSIONS,
  SRU_EXPORT_PERMISSIONS,
  SIE_IMPORT_PERMISSIONS,
  INVOICING_SETTINGS_PERMISSIONS,
  PAYMENT_TERMS_PERMISSIONS,
  UNITS_PERMISSIONS,
  CURRENCIES_PERMISSIONS,
  DELIVERY_METHODS_PERMISSIONS,
  DELIVERY_TERMS_PERMISSIONS,
  PRICE_LISTS_PERMISSIONS,
  INVOICE_TEMPLATES_PERMISSIONS,
  EXCHANGE_RATES_PERMISSIONS,
  ACCRUAL_PERMISSIONS,
  FIXED_ASSET_PERMISSIONS,
  DEPRECIATION_PERMISSIONS,
  type Permission,
} from "./permissions"

export type SystemRole =
  | "super_admin"
  | "agency_owner"
  | "agency_admin"
  | "agency_staff"
  | "agency_viewer"
  | "customer_owner"
  | "customer_admin"
  | "customer_user"
  | "customer_viewer"

// ─────────────────────────────────────────────
// SUPER ADMIN — full platform access
// ─────────────────────────────────────────────
const SUPER_ADMIN_PERMISSIONS: Permission[] = [
  // Platform
  ...Object.values(PLATFORM_PERMISSIONS),
  // Full org-level access (can enter any org context)
  ...Object.values(INVOICE_PERMISSIONS),
  ...Object.values(CONTACT_PERMISSIONS),
  ...Object.values(PRODUCT_PERMISSIONS),
  ...Object.values(PAYMENT_PERMISSIONS),
  ...Object.values(CONTRACT_PERMISSIONS),
  ...Object.values(USER_PERMISSIONS),
  ...Object.values(SETTINGS_PERMISSIONS),
  ...Object.values(REPORT_PERMISSIONS),
  ...Object.values(ACCOUNTING_PERMISSIONS),
  ...Object.values(SUPPLIER_INVOICE_PERMISSIONS),
  ...Object.values(INVENTORY_PERMISSIONS),
  ...Object.values(AGENCY_PERMISSIONS),
  ...Object.values(TASK_PERMISSIONS),
  ...Object.values(SIGNATURE_PERMISSIONS),
  ...Object.values(BRANDING_PERMISSIONS),
  ...Object.values(SRU_EXPORT_PERMISSIONS),
  ...Object.values(SIE_IMPORT_PERMISSIONS),
  ...Object.values(ACCRUAL_PERMISSIONS),
  ...Object.values(FIXED_ASSET_PERMISSIONS),
  ...Object.values(DEPRECIATION_PERMISSIONS),
  ...Object.values(INVOICING_SETTINGS_PERMISSIONS),
  ...Object.values(PAYMENT_TERMS_PERMISSIONS),
  ...Object.values(UNITS_PERMISSIONS),
  ...Object.values(CURRENCIES_PERMISSIONS),
  ...Object.values(DELIVERY_METHODS_PERMISSIONS),
  ...Object.values(DELIVERY_TERMS_PERMISSIONS),
  ...Object.values(PRICE_LISTS_PERMISSIONS),
  ...Object.values(INVOICE_TEMPLATES_PERMISSIONS),
  ...Object.values(EXCHANGE_RATES_PERMISSIONS),
]

// ─────────────────────────────────────────────
// AGENCY OWNER — full access to own agency + all managed clients
// ─────────────────────────────────────────────
const AGENCY_OWNER_PERMISSIONS: Permission[] = [
  // Invoices
  INVOICE_PERMISSIONS.READ,
  INVOICE_PERMISSIONS.CREATE,
  INVOICE_PERMISSIONS.UPDATE,
  INVOICE_PERMISSIONS.DELETE,
  INVOICE_PERMISSIONS.SEND,
  INVOICE_PERMISSIONS.VOID,
  INVOICE_PERMISSIONS.EXPORT,
  // Contacts
  CONTACT_PERMISSIONS.READ,
  CONTACT_PERMISSIONS.CREATE,
  CONTACT_PERMISSIONS.UPDATE,
  CONTACT_PERMISSIONS.DELETE,
  // Products
  PRODUCT_PERMISSIONS.READ,
  PRODUCT_PERMISSIONS.CREATE,
  PRODUCT_PERMISSIONS.UPDATE,
  PRODUCT_PERMISSIONS.DELETE,
  // Payments
  PAYMENT_PERMISSIONS.READ,
  PAYMENT_PERMISSIONS.CREATE,
  PAYMENT_PERMISSIONS.DELETE,
  // Contracts
  CONTRACT_PERMISSIONS.READ,
  CONTRACT_PERMISSIONS.CREATE,
  CONTRACT_PERMISSIONS.UPDATE,
  CONTRACT_PERMISSIONS.DELETE,
  // Users
  USER_PERMISSIONS.READ,
  USER_PERMISSIONS.INVITE,
  USER_PERMISSIONS.UPDATE_ROLE,
  USER_PERMISSIONS.REMOVE,
  // Settings
  SETTINGS_PERMISSIONS.READ,
  SETTINGS_PERMISSIONS.UPDATE,
  SETTINGS_PERMISSIONS.MANAGE_BILLING,
  SETTINGS_PERMISSIONS.DELETE_ORG,
  // Reports
  REPORT_PERMISSIONS.READ,
  REPORT_PERMISSIONS.EXPORT,
  // Accounting — full access (agencies manage client books)
  ACCOUNTING_PERMISSIONS.READ,
  ACCOUNTING_PERMISSIONS.POST,
  ACCOUNTING_PERMISSIONS.MANAGE_ACCOUNTS,
  ACCOUNTING_PERMISSIONS.MANAGE_PERIODS,
  ACCOUNTING_PERMISSIONS.EXPORT,
  ACCOUNTING_PERMISSIONS.IMPORT_SIE,
  ACCOUNTING_PERMISSIONS.YEAR_END_READ,
  ACCOUNTING_PERMISSIONS.YEAR_END_CLOSE,
  // Supplier invoices — full access (including approvals)
  ...Object.values(SUPPLIER_INVOICE_PERMISSIONS),
  // Inventory — full access
  ...Object.values(INVENTORY_PERMISSIONS),
  // Agency
  AGENCY_PERMISSIONS.READ_CLIENTS,
  AGENCY_PERMISSIONS.MANAGE_CLIENTS,
  AGENCY_PERMISSIONS.SWITCH_TO_CLIENT,
  AGENCY_PERMISSIONS.GRANT_STAFF_ACCESS,
  // Tasks — full access
  ...Object.values(TASK_PERMISSIONS),
  // Signatures — full access
  ...Object.values(SIGNATURE_PERMISSIONS),
  // Quotes — full access
  ...Object.values(QUOTE_PERMISSIONS),
  // Branding — full access incl. white-label
  ...Object.values(BRANDING_PERMISSIONS),
  // Fixed assets + accruals — full access
  ...Object.values(FIXED_ASSET_PERMISSIONS),
  ...Object.values(DEPRECIATION_PERMISSIONS),
  ...Object.values(ACCRUAL_PERMISSIONS),
  // SIE import + SRU export — full access
  ...Object.values(SIE_IMPORT_PERMISSIONS),
  ...Object.values(SRU_EXPORT_PERMISSIONS),
  // Invoicing settings — full access
  ...Object.values(INVOICING_SETTINGS_PERMISSIONS),
  ...Object.values(PAYMENT_TERMS_PERMISSIONS),
  ...Object.values(UNITS_PERMISSIONS),
  ...Object.values(CURRENCIES_PERMISSIONS),
  ...Object.values(DELIVERY_METHODS_PERMISSIONS),
  ...Object.values(DELIVERY_TERMS_PERMISSIONS),
  ...Object.values(PRICE_LISTS_PERMISSIONS),
  ...Object.values(INVOICE_TEMPLATES_PERMISSIONS),
  ...Object.values(EXCHANGE_RATES_PERMISSIONS),
]

// ─────────────────────────────────────────────
// AGENCY ADMIN — manage agency + clients, no billing/delete
// ─────────────────────────────────────────────
const AGENCY_ADMIN_PERMISSIONS: Permission[] = [
  // Invoices
  INVOICE_PERMISSIONS.READ,
  INVOICE_PERMISSIONS.CREATE,
  INVOICE_PERMISSIONS.UPDATE,
  INVOICE_PERMISSIONS.DELETE,
  INVOICE_PERMISSIONS.SEND,
  INVOICE_PERMISSIONS.VOID,
  INVOICE_PERMISSIONS.EXPORT,
  // Contacts
  CONTACT_PERMISSIONS.READ,
  CONTACT_PERMISSIONS.CREATE,
  CONTACT_PERMISSIONS.UPDATE,
  CONTACT_PERMISSIONS.DELETE,
  // Products
  PRODUCT_PERMISSIONS.READ,
  PRODUCT_PERMISSIONS.CREATE,
  PRODUCT_PERMISSIONS.UPDATE,
  PRODUCT_PERMISSIONS.DELETE,
  // Payments
  PAYMENT_PERMISSIONS.READ,
  PAYMENT_PERMISSIONS.CREATE,
  PAYMENT_PERMISSIONS.DELETE,
  // Contracts
  CONTRACT_PERMISSIONS.READ,
  CONTRACT_PERMISSIONS.CREATE,
  CONTRACT_PERMISSIONS.UPDATE,
  CONTRACT_PERMISSIONS.DELETE,
  // Users
  USER_PERMISSIONS.READ,
  USER_PERMISSIONS.INVITE,
  USER_PERMISSIONS.UPDATE_ROLE,
  USER_PERMISSIONS.REMOVE,
  // Settings (no billing, no delete)
  SETTINGS_PERMISSIONS.READ,
  SETTINGS_PERMISSIONS.UPDATE,
  // Reports
  REPORT_PERMISSIONS.READ,
  REPORT_PERMISSIONS.EXPORT,
  // Accounting — full (admins manage books)
  ACCOUNTING_PERMISSIONS.READ,
  ACCOUNTING_PERMISSIONS.POST,
  ACCOUNTING_PERMISSIONS.MANAGE_ACCOUNTS,
  ACCOUNTING_PERMISSIONS.MANAGE_PERIODS,
  ACCOUNTING_PERMISSIONS.EXPORT,
  ACCOUNTING_PERMISSIONS.IMPORT_SIE,
  ACCOUNTING_PERMISSIONS.YEAR_END_READ,
  ACCOUNTING_PERMISSIONS.YEAR_END_CLOSE,
  // Supplier invoices — full access
  ...Object.values(SUPPLIER_INVOICE_PERMISSIONS),
  // Inventory — full access
  ...Object.values(INVENTORY_PERMISSIONS),
  // Agency
  AGENCY_PERMISSIONS.READ_CLIENTS,
  AGENCY_PERMISSIONS.MANAGE_CLIENTS,
  AGENCY_PERMISSIONS.SWITCH_TO_CLIENT,
  AGENCY_PERMISSIONS.GRANT_STAFF_ACCESS,
  // Tasks — full access
  ...Object.values(TASK_PERMISSIONS),
  // Signatures — full access
  ...Object.values(SIGNATURE_PERMISSIONS),
  // Quotes — full access (no cancel for admin)
  QUOTE_PERMISSIONS.READ,
  QUOTE_PERMISSIONS.CREATE,
  QUOTE_PERMISSIONS.UPDATE,
  QUOTE_PERMISSIONS.SEND,
  QUOTE_PERMISSIONS.CONVERT,
  // Branding — read + update (no white-label toggle for admin)
  BRANDING_PERMISSIONS.READ,
  BRANDING_PERMISSIONS.UPDATE,
  BRANDING_PERMISSIONS.UPLOAD_ASSETS,
  // Fixed assets + accruals — full access
  ...Object.values(FIXED_ASSET_PERMISSIONS),
  ...Object.values(DEPRECIATION_PERMISSIONS),
  ...Object.values(ACCRUAL_PERMISSIONS),
  // SIE import + SRU export — full access
  ...Object.values(SIE_IMPORT_PERMISSIONS),
  ...Object.values(SRU_EXPORT_PERMISSIONS),
  // Invoicing settings — full access
  ...Object.values(INVOICING_SETTINGS_PERMISSIONS),
  ...Object.values(PAYMENT_TERMS_PERMISSIONS),
  ...Object.values(UNITS_PERMISSIONS),
  ...Object.values(CURRENCIES_PERMISSIONS),
  ...Object.values(DELIVERY_METHODS_PERMISSIONS),
  ...Object.values(DELIVERY_TERMS_PERMISSIONS),
  ...Object.values(PRICE_LISTS_PERMISSIONS),
  ...Object.values(INVOICE_TEMPLATES_PERMISSIONS),
  ...Object.values(EXCHANGE_RATES_PERMISSIONS),
]

// ─────────────────────────────────────────────
// AGENCY STAFF — day-to-day invoicing work
//   Can access clients they have been explicitly granted
// ─────────────────────────────────────────────
const AGENCY_STAFF_PERMISSIONS: Permission[] = [
  // Invoices (no delete, no void)
  INVOICE_PERMISSIONS.READ,
  INVOICE_PERMISSIONS.CREATE,
  INVOICE_PERMISSIONS.UPDATE,
  INVOICE_PERMISSIONS.SEND,
  INVOICE_PERMISSIONS.EXPORT,
  // Contacts (no delete)
  CONTACT_PERMISSIONS.READ,
  CONTACT_PERMISSIONS.CREATE,
  CONTACT_PERMISSIONS.UPDATE,
  // Products (read only)
  PRODUCT_PERMISSIONS.READ,
  // Payments
  PAYMENT_PERMISSIONS.READ,
  PAYMENT_PERMISSIONS.CREATE,
  // Contracts
  CONTRACT_PERMISSIONS.READ,
  CONTRACT_PERMISSIONS.CREATE,
  CONTRACT_PERMISSIONS.UPDATE,
  // Reports (read only)
  REPORT_PERMISSIONS.READ,
  // Accounting — read only for staff
  ACCOUNTING_PERMISSIONS.READ,
  ACCOUNTING_PERMISSIONS.YEAR_END_READ,
  // Supplier invoices — upload + review + attest (no book/pay, no manage_approvals)
  SUPPLIER_INVOICE_PERMISSIONS.READ,
  SUPPLIER_INVOICE_PERMISSIONS.UPLOAD,
  SUPPLIER_INVOICE_PERMISSIONS.REVIEW,
  SUPPLIER_INVOICE_PERMISSIONS.ATTEST,
  // Agency (can switch to granted clients)
  AGENCY_PERMISSIONS.READ_CLIENTS,
  AGENCY_PERMISSIONS.SWITCH_TO_CLIENT,
  // Tasks — create + manage own + comment + assign
  TASK_PERMISSIONS.READ,
  TASK_PERMISSIONS.CREATE,
  TASK_PERMISSIONS.UPDATE_OWN,
  TASK_PERMISSIONS.DELETE_OWN,
  TASK_PERMISSIONS.ASSIGN,
  TASK_PERMISSIONS.COMMENT,
  // Signatures — can view and send (create + remind), cancel own
  SIGNATURE_PERMISSIONS.READ,
  SIGNATURE_PERMISSIONS.CREATE,
  SIGNATURE_PERMISSIONS.SEND,
  SIGNATURE_PERMISSIONS.REMIND,
  // Quotes — create + send, no cancel/convert
  QUOTE_PERMISSIONS.READ,
  QUOTE_PERMISSIONS.CREATE,
  QUOTE_PERMISSIONS.UPDATE,
  QUOTE_PERMISSIONS.SEND,
  // Fixed assets + accruals — read; SIE import — read
  FIXED_ASSET_PERMISSIONS.READ,
  DEPRECIATION_PERMISSIONS.READ,
  DEPRECIATION_PERMISSIONS.POST,
  ACCRUAL_PERMISSIONS.READ,
  SIE_IMPORT_PERMISSIONS.READ,
  SRU_EXPORT_PERMISSIONS.READ,
  INVOICING_SETTINGS_PERMISSIONS.READ,
  PAYMENT_TERMS_PERMISSIONS.READ,
  UNITS_PERMISSIONS.READ,
  CURRENCIES_PERMISSIONS.READ,
  DELIVERY_METHODS_PERMISSIONS.READ,
  DELIVERY_TERMS_PERMISSIONS.READ,
  PRICE_LISTS_PERMISSIONS.READ,
  INVOICE_TEMPLATES_PERMISSIONS.READ,
  EXCHANGE_RATES_PERMISSIONS.READ,
]

// ─────────────────────────────────────────────
// AGENCY VIEWER — read-only access to agency context
// ─────────────────────────────────────────────
const AGENCY_VIEWER_PERMISSIONS: Permission[] = [
  INVOICE_PERMISSIONS.READ,
  CONTACT_PERMISSIONS.READ,
  PRODUCT_PERMISSIONS.READ,
  PAYMENT_PERMISSIONS.READ,
  CONTRACT_PERMISSIONS.READ,
  REPORT_PERMISSIONS.READ,
  ACCOUNTING_PERMISSIONS.READ,
  ACCOUNTING_PERMISSIONS.YEAR_END_READ,
  SUPPLIER_INVOICE_PERMISSIONS.READ,
  AGENCY_PERMISSIONS.READ_CLIENTS,
  TASK_PERMISSIONS.READ,
  QUOTE_PERMISSIONS.READ,
  FIXED_ASSET_PERMISSIONS.READ,
  DEPRECIATION_PERMISSIONS.READ,
  ACCRUAL_PERMISSIONS.READ,
  SIE_IMPORT_PERMISSIONS.READ,
  SRU_EXPORT_PERMISSIONS.READ,
  INVOICING_SETTINGS_PERMISSIONS.READ,
  PAYMENT_TERMS_PERMISSIONS.READ,
  UNITS_PERMISSIONS.READ,
  CURRENCIES_PERMISSIONS.READ,
  DELIVERY_METHODS_PERMISSIONS.READ,
  DELIVERY_TERMS_PERMISSIONS.READ,
  PRICE_LISTS_PERMISSIONS.READ,
  INVOICE_TEMPLATES_PERMISSIONS.READ,
  EXCHANGE_RATES_PERMISSIONS.READ,
]

// ─────────────────────────────────────────────
// CUSTOMER OWNER — full control of own account
// ─────────────────────────────────────────────
const CUSTOMER_OWNER_PERMISSIONS: Permission[] = [
  // Invoices
  INVOICE_PERMISSIONS.READ,
  INVOICE_PERMISSIONS.CREATE,
  INVOICE_PERMISSIONS.UPDATE,
  INVOICE_PERMISSIONS.DELETE,
  INVOICE_PERMISSIONS.SEND,
  INVOICE_PERMISSIONS.VOID,
  INVOICE_PERMISSIONS.EXPORT,
  // Contacts
  CONTACT_PERMISSIONS.READ,
  CONTACT_PERMISSIONS.CREATE,
  CONTACT_PERMISSIONS.UPDATE,
  CONTACT_PERMISSIONS.DELETE,
  // Products
  PRODUCT_PERMISSIONS.READ,
  PRODUCT_PERMISSIONS.CREATE,
  PRODUCT_PERMISSIONS.UPDATE,
  PRODUCT_PERMISSIONS.DELETE,
  // Payments
  PAYMENT_PERMISSIONS.READ,
  PAYMENT_PERMISSIONS.CREATE,
  PAYMENT_PERMISSIONS.DELETE,
  // Contracts
  CONTRACT_PERMISSIONS.READ,
  CONTRACT_PERMISSIONS.CREATE,
  CONTRACT_PERMISSIONS.UPDATE,
  CONTRACT_PERMISSIONS.DELETE,
  // Users
  USER_PERMISSIONS.READ,
  USER_PERMISSIONS.INVITE,
  USER_PERMISSIONS.UPDATE_ROLE,
  USER_PERMISSIONS.REMOVE,
  // Settings
  SETTINGS_PERMISSIONS.READ,
  SETTINGS_PERMISSIONS.UPDATE,
  SETTINGS_PERMISSIONS.MANAGE_BILLING,
  SETTINGS_PERMISSIONS.DELETE_ORG,
  // Reports
  REPORT_PERMISSIONS.READ,
  REPORT_PERMISSIONS.EXPORT,
  // Accounting — full access for owner
  ACCOUNTING_PERMISSIONS.READ,
  ACCOUNTING_PERMISSIONS.POST,
  ACCOUNTING_PERMISSIONS.MANAGE_ACCOUNTS,
  ACCOUNTING_PERMISSIONS.MANAGE_PERIODS,
  ACCOUNTING_PERMISSIONS.EXPORT,
  ACCOUNTING_PERMISSIONS.IMPORT_SIE,
  ACCOUNTING_PERMISSIONS.YEAR_END_READ,
  ACCOUNTING_PERMISSIONS.YEAR_END_CLOSE,
  // Supplier invoices — full access
  ...Object.values(SUPPLIER_INVOICE_PERMISSIONS),
  // Inventory — full access
  ...Object.values(INVENTORY_PERMISSIONS),
  // Tasks — full access
  ...Object.values(TASK_PERMISSIONS),
  // Signatures — full access
  ...Object.values(SIGNATURE_PERMISSIONS),
  // Quotes — full access
  ...Object.values(QUOTE_PERMISSIONS),
  // Branding — full access
  ...Object.values(BRANDING_PERMISSIONS),
  // Fixed assets + accruals — full access
  ...Object.values(FIXED_ASSET_PERMISSIONS),
  ...Object.values(DEPRECIATION_PERMISSIONS),
  ...Object.values(ACCRUAL_PERMISSIONS),
  // SIE import + SRU export — full access
  ...Object.values(SIE_IMPORT_PERMISSIONS),
  ...Object.values(SRU_EXPORT_PERMISSIONS),
  // Invoicing settings — full access
  ...Object.values(INVOICING_SETTINGS_PERMISSIONS),
  ...Object.values(PAYMENT_TERMS_PERMISSIONS),
  ...Object.values(UNITS_PERMISSIONS),
  ...Object.values(CURRENCIES_PERMISSIONS),
  ...Object.values(DELIVERY_METHODS_PERMISSIONS),
  ...Object.values(DELIVERY_TERMS_PERMISSIONS),
  ...Object.values(PRICE_LISTS_PERMISSIONS),
  ...Object.values(INVOICE_TEMPLATES_PERMISSIONS),
  ...Object.values(EXCHANGE_RATES_PERMISSIONS),
]

// ─────────────────────────────────────────────
// CUSTOMER ADMIN — manage account, no billing/delete
// ─────────────────────────────────────────────
const CUSTOMER_ADMIN_PERMISSIONS: Permission[] = [
  // Invoices
  INVOICE_PERMISSIONS.READ,
  INVOICE_PERMISSIONS.CREATE,
  INVOICE_PERMISSIONS.UPDATE,
  INVOICE_PERMISSIONS.DELETE,
  INVOICE_PERMISSIONS.SEND,
  INVOICE_PERMISSIONS.VOID,
  INVOICE_PERMISSIONS.EXPORT,
  // Contacts
  CONTACT_PERMISSIONS.READ,
  CONTACT_PERMISSIONS.CREATE,
  CONTACT_PERMISSIONS.UPDATE,
  CONTACT_PERMISSIONS.DELETE,
  // Products
  PRODUCT_PERMISSIONS.READ,
  PRODUCT_PERMISSIONS.CREATE,
  PRODUCT_PERMISSIONS.UPDATE,
  // Payments
  PAYMENT_PERMISSIONS.READ,
  PAYMENT_PERMISSIONS.CREATE,
  // Contracts
  CONTRACT_PERMISSIONS.READ,
  CONTRACT_PERMISSIONS.CREATE,
  CONTRACT_PERMISSIONS.UPDATE,
  // Users (no role changes)
  USER_PERMISSIONS.READ,
  USER_PERMISSIONS.INVITE,
  // Settings (read only)
  SETTINGS_PERMISSIONS.READ,
  // Reports
  REPORT_PERMISSIONS.READ,
  REPORT_PERMISSIONS.EXPORT,
  // Accounting — admin can post + manage accounts
  ACCOUNTING_PERMISSIONS.READ,
  ACCOUNTING_PERMISSIONS.POST,
  ACCOUNTING_PERMISSIONS.MANAGE_ACCOUNTS,
  ACCOUNTING_PERMISSIONS.EXPORT,
  ACCOUNTING_PERMISSIONS.IMPORT_SIE,
  ACCOUNTING_PERMISSIONS.YEAR_END_READ,
  // Supplier invoices — full access (admins handle AP)
  ...Object.values(SUPPLIER_INVOICE_PERMISSIONS),
  // Inventory — full access
  ...Object.values(INVENTORY_PERMISSIONS),
  // Tasks — full access
  ...Object.values(TASK_PERMISSIONS),
  // Signatures — full access
  ...Object.values(SIGNATURE_PERMISSIONS),
  // Quotes — full access (no cancel)
  QUOTE_PERMISSIONS.READ,
  QUOTE_PERMISSIONS.CREATE,
  QUOTE_PERMISSIONS.UPDATE,
  QUOTE_PERMISSIONS.SEND,
  QUOTE_PERMISSIONS.CONVERT,
  // Branding — read + update (no white-label toggle)
  BRANDING_PERMISSIONS.READ,
  BRANDING_PERMISSIONS.UPDATE,
  BRANDING_PERMISSIONS.UPLOAD_ASSETS,
  // Fixed assets + accruals — full access
  ...Object.values(FIXED_ASSET_PERMISSIONS),
  ...Object.values(DEPRECIATION_PERMISSIONS),
  ...Object.values(ACCRUAL_PERMISSIONS),
  // SIE import + SRU export — full access
  ...Object.values(SIE_IMPORT_PERMISSIONS),
  ...Object.values(SRU_EXPORT_PERMISSIONS),
  // Invoicing settings — full access
  ...Object.values(INVOICING_SETTINGS_PERMISSIONS),
  ...Object.values(PAYMENT_TERMS_PERMISSIONS),
  ...Object.values(UNITS_PERMISSIONS),
  ...Object.values(CURRENCIES_PERMISSIONS),
  ...Object.values(DELIVERY_METHODS_PERMISSIONS),
  ...Object.values(DELIVERY_TERMS_PERMISSIONS),
  ...Object.values(PRICE_LISTS_PERMISSIONS),
  ...Object.values(INVOICE_TEMPLATES_PERMISSIONS),
  ...Object.values(EXCHANGE_RATES_PERMISSIONS),
]

// ─────────────────────────────────────────────
// CUSTOMER USER — core invoicing tasks
// ─────────────────────────────────────────────
const CUSTOMER_USER_PERMISSIONS: Permission[] = [
  // Invoices (no delete, no void)
  INVOICE_PERMISSIONS.READ,
  INVOICE_PERMISSIONS.CREATE,
  INVOICE_PERMISSIONS.UPDATE,
  INVOICE_PERMISSIONS.SEND,
  INVOICE_PERMISSIONS.EXPORT,
  // Contacts (no delete)
  CONTACT_PERMISSIONS.READ,
  CONTACT_PERMISSIONS.CREATE,
  CONTACT_PERMISSIONS.UPDATE,
  // Products (read only)
  PRODUCT_PERMISSIONS.READ,
  // Payments
  PAYMENT_PERMISSIONS.READ,
  PAYMENT_PERMISSIONS.CREATE,
  // Contracts
  CONTRACT_PERMISSIONS.READ,
  CONTRACT_PERMISSIONS.CREATE,
  CONTRACT_PERMISSIONS.UPDATE,
  // Reports
  REPORT_PERMISSIONS.READ,
  // Accounting — read only for regular users
  ACCOUNTING_PERMISSIONS.READ,
  ACCOUNTING_PERMISSIONS.YEAR_END_READ,
  // Supplier invoices — upload + review + attest (no book/pay, no manage_approvals)
  SUPPLIER_INVOICE_PERMISSIONS.READ,
  SUPPLIER_INVOICE_PERMISSIONS.UPLOAD,
  SUPPLIER_INVOICE_PERMISSIONS.REVIEW,
  SUPPLIER_INVOICE_PERMISSIONS.ATTEST,
  // Inventory — read + write transactions
  INVENTORY_PERMISSIONS.READ,
  INVENTORY_PERMISSIONS.WRITE,
  // Tasks — create + manage own + comment
  TASK_PERMISSIONS.READ,
  TASK_PERMISSIONS.CREATE,
  TASK_PERMISSIONS.UPDATE_OWN,
  TASK_PERMISSIONS.DELETE_OWN,
  TASK_PERMISSIONS.COMMENT,
  // Signatures — create + send + remind
  SIGNATURE_PERMISSIONS.READ,
  SIGNATURE_PERMISSIONS.CREATE,
  SIGNATURE_PERMISSIONS.SEND,
  SIGNATURE_PERMISSIONS.REMIND,
  // Quotes — create + send, no cancel/convert
  QUOTE_PERMISSIONS.READ,
  QUOTE_PERMISSIONS.CREATE,
  QUOTE_PERMISSIONS.UPDATE,
  QUOTE_PERMISSIONS.SEND,
  // Fixed assets + accruals — read; SIE import — read
  FIXED_ASSET_PERMISSIONS.READ,
  DEPRECIATION_PERMISSIONS.READ,
  DEPRECIATION_PERMISSIONS.POST,
  ACCRUAL_PERMISSIONS.READ,
  SIE_IMPORT_PERMISSIONS.READ,
  SRU_EXPORT_PERMISSIONS.READ,
  INVOICING_SETTINGS_PERMISSIONS.READ,
  PAYMENT_TERMS_PERMISSIONS.READ,
  UNITS_PERMISSIONS.READ,
  CURRENCIES_PERMISSIONS.READ,
  DELIVERY_METHODS_PERMISSIONS.READ,
  DELIVERY_TERMS_PERMISSIONS.READ,
  PRICE_LISTS_PERMISSIONS.READ,
  INVOICE_TEMPLATES_PERMISSIONS.READ,
  EXCHANGE_RATES_PERMISSIONS.READ,
]

// ─────────────────────────────────────────────
// CUSTOMER VIEWER — read-only
// ─────────────────────────────────────────────
const CUSTOMER_VIEWER_PERMISSIONS: Permission[] = [
  INVOICE_PERMISSIONS.READ,
  CONTACT_PERMISSIONS.READ,
  PRODUCT_PERMISSIONS.READ,
  PAYMENT_PERMISSIONS.READ,
  CONTRACT_PERMISSIONS.READ,
  REPORT_PERMISSIONS.READ,
  ACCOUNTING_PERMISSIONS.READ,
  SUPPLIER_INVOICE_PERMISSIONS.READ,
  INVENTORY_PERMISSIONS.READ,
  TASK_PERMISSIONS.READ,
  QUOTE_PERMISSIONS.READ,
  FIXED_ASSET_PERMISSIONS.READ,
  DEPRECIATION_PERMISSIONS.READ,
  ACCRUAL_PERMISSIONS.READ,
  SIE_IMPORT_PERMISSIONS.READ,
  SRU_EXPORT_PERMISSIONS.READ,
  INVOICING_SETTINGS_PERMISSIONS.READ,
  PAYMENT_TERMS_PERMISSIONS.READ,
  UNITS_PERMISSIONS.READ,
  CURRENCIES_PERMISSIONS.READ,
  DELIVERY_METHODS_PERMISSIONS.READ,
  DELIVERY_TERMS_PERMISSIONS.READ,
  PRICE_LISTS_PERMISSIONS.READ,
  INVOICE_TEMPLATES_PERMISSIONS.READ,
  EXCHANGE_RATES_PERMISSIONS.READ,
]

// ─────────────────────────────────────────────
// Role → Permission Set lookup
// ─────────────────────────────────────────────
export const ROLE_PERMISSIONS: Record<SystemRole, ReadonlySet<Permission>> = {
  super_admin:     new Set(SUPER_ADMIN_PERMISSIONS),
  agency_owner:    new Set(AGENCY_OWNER_PERMISSIONS),
  agency_admin:    new Set(AGENCY_ADMIN_PERMISSIONS),
  agency_staff:    new Set(AGENCY_STAFF_PERMISSIONS),
  agency_viewer:   new Set(AGENCY_VIEWER_PERMISSIONS),
  customer_owner:  new Set(CUSTOMER_OWNER_PERMISSIONS),
  customer_admin:  new Set(CUSTOMER_ADMIN_PERMISSIONS),
  customer_user:   new Set(CUSTOMER_USER_PERMISSIONS),
  customer_viewer: new Set(CUSTOMER_VIEWER_PERMISSIONS),
}

// ─────────────────────────────────────────────
// Agency access-level overrides
// When agency staff impersonates a client with a restricted
// access level, apply this subset of their permissions.
// ─────────────────────────────────────────────
export const ACCESS_LEVEL_ALLOWED_PERMISSIONS: Record<
  "full" | "invoicing_only" | "read_only",
  ReadonlySet<Permission>
> = {
  full: new Set([
    ...Object.values(INVOICE_PERMISSIONS),
    ...Object.values(CONTACT_PERMISSIONS),
    ...Object.values(PRODUCT_PERMISSIONS),
    ...Object.values(PAYMENT_PERMISSIONS),
    REPORT_PERMISSIONS.READ,
    REPORT_PERMISSIONS.EXPORT,
  ]),
  invoicing_only: new Set([
    INVOICE_PERMISSIONS.READ,
    INVOICE_PERMISSIONS.CREATE,
    INVOICE_PERMISSIONS.UPDATE,
    INVOICE_PERMISSIONS.SEND,
    INVOICE_PERMISSIONS.EXPORT,
    CONTACT_PERMISSIONS.READ,
    PRODUCT_PERMISSIONS.READ,
    PAYMENT_PERMISSIONS.READ,
    PAYMENT_PERMISSIONS.CREATE,
  ]),
  read_only: new Set([
    INVOICE_PERMISSIONS.READ,
    CONTACT_PERMISSIONS.READ,
    PRODUCT_PERMISSIONS.READ,
    PAYMENT_PERMISSIONS.READ,
    REPORT_PERMISSIONS.READ,
  ]),
}
